version: '3'

services:
  clone_github:
    build:
      context: .
      dockerfile: Dockerfile.clone
    volumes:
      - proyecto:/volumen/php
      - sql:/volumen/mysql

  # No creo el usuario de mysql ni la bbdd porque la cremos con el script
  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      # MYSQL_USER: dwes
      MYSQL_PASSWORD: dwes
      # MYSQL_DATABASE: dwes
    volumes:
      - sql:/docker-entrypoint-initdb.d

  apache:
    build: apache/
    ports:
      - 80:80
    volumes:
      - proyecto:/var/www/html/
    depends_on:
      - php
      - clone_github

  php:
    build: php/
    ports:
      - 9000:9000
    volumes:
      - proyecto:/var/www/html/
    depends_on:
      - mysql
      - clone_github 

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8082:80
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    depends_on:
      - mysql

volumes:
  proyecto:
  sql: